In [5]:
import sys
sys.path.append(r"C:\Users\Windows\PycharmProjects\Personal_FC\Job portal")

import pandas as pd
import psycopg2
from config import DB_CONFIG

conn = psycopg2.connect(**DB_CONFIG)

df = pd.read_sql("""
    SELECT
        j.title,
        j.department,
        j.location,
        j.first_published,
        j.updated_at,
        j.pay_min,
        j.pay_max,
        j.currency,
        j.description,
        c.name as company
    FROM jobs j
    JOIN companies c ON j.company_id = c.id
""", conn)

conn.close()
df

C:\Users\Windows\AppData\Local\Temp\ipykernel_35396\2615214953.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("""
C:\Users\Windows\AppData\Local\Temp\ipykernel_35396\2615214953.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("""

,title,department,location,first_published,updated_at,pay_min,pay_max,currency,description,company
0,"Account Executive, Academic Medical Centers",Sales,"New York City, NY; San Francisco, CA",2026-01-30 13:57:16+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
1,"Account Executive, Beneficial Deployments - EMEA",Sales,"Dublin, IE",2026-03-26 10:01:05+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
2,"Account Executive, Beneficial Deployments - EMEA",Sales,"London, UK",2026-03-25 15:21:19+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
3,"Account Executive, Beneficial Deployments (Fre...",Sales,"Dublin, IE",2026-03-26 10:01:22+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
4,"Account Executive, Beneficial Deployments (Fre...",Sales,"London, UK",2026-03-25 14:53:39+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
...,...,...,...,...,...,...,...,...,...,...
2574,Solutions Engineer,Sales,San Francisco,2026-05-20 20:47:52+01:00,2026-06-04 17:53:39+01:00,None,None,None,The Solutions team at Asana drives customer ac...,Asana
2575,Staff Data Scientist,Product Data,"Vancouver, BC",2026-04-23 22:25:54+01:00,2026-06-04 17:53:39+01:00,None,None,None,We're looking for a Staff Data Scientist to he...,Asana
2576,Sales Executive,Sales,United States (Remote-First),2026-06-09 14:13:39+01:00,2026-06-09 14:13:39+01:00,None,None,None,About Us\n\n\nOur leading SaaS-based Global Em...,G-P
2577,Sr. Director & Head of Architecture,Technology,United Kingdom - Northern Ireland (Remote-First),2026-06-09 11:15:30+01:00,2026-06-09 11:15:30+01:00,None,None,None,About Us\n\n\nOur leading SaaS-based Global Em...,G-P
2578,Sr. Director & Head of Architecture,Technology,United States (Remote-First),2026-06-09 11:18:04+01:00,2026-06-09 11:18:04+01:00,None,None,None,About Us\n\n\nOur leading SaaS-based Global Em...,G-P

,title,department,location,first_published,updated_at,pay_min,pay_max,currency,description,company
0,"Account Executive, Academic Medical Centers",Sales,"New York City, NY; San Francisco, CA",2026-01-30 13:57:16+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
1,"Account Executive, Beneficial Deployments - EMEA",Sales,"Dublin, IE",2026-03-26 10:01:05+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
2,"Account Executive, Beneficial Deployments - EMEA",Sales,"London, UK",2026-03-25 15:21:19+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
3,"Account Executive, Beneficial Deployments (Fre...",Sales,"Dublin, IE",2026-03-26 10:01:22+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
4,"Account Executive, Beneficial Deployments (Fre...",Sales,"London, UK",2026-03-25 14:53:39+00:00,2026-04-01 15:49:08+01:00,None,None,None,About Anthropic\n\n\nAnthropic’s mission is to...,Anthropic
...,...,...,...,...,...,...,...,...,...,...
2574,Solutions Engineer,Sales,San Francisco,2026-05-20 20:47:52+01:00,2026-06-04 17:53:39+01:00,None,None,None,The Solutions team at Asana drives customer ac...,Asana
2575,Staff Data Scientist,Product Data,"Vancouver, BC",2026-04-23 22:25:54+01:00,2026-06-04 17:53:39+01:00,None,None,None,We're looking for a Staff Data Scientist to he...,Asana
2576,Sales Executive,Sales,United States (Remote-First),2026-06-09 14:13:39+01:00,2026-06-09 14:13:39+01:00,None,None,None,About Us\n\n\nOur leading SaaS-based Global Em...,G-P
2577,Sr. Director & Head of Architecture,Technology,United Kingdom - Northern Ireland (Remote-First),2026-06-09 11:15:30+01:00,2026-06-09 11:15:30+01:00,None,None,None,About Us\n\n\nOur leading SaaS-based Global Em...,G-P
2578,Sr. Director & Head of Architecture,Technology,United States (Remote-First),2026-06-09 11:18:04+01:00,2026-06-09 11:18:04+01:00,None,None,None,About Us\n\n\nOur leading SaaS-based Global Em...,G-P

In [6]:
mdf = df[["title","company","department","location","description"]]

In [7]:
mdf.loc[mdf.location.str.contains('Dublin','Ireland')]
mdf.loc[mdf.location.str.contains("Ireland")]

,title,company,department,location,description
554,"Senior Technical Revenue Analyst (Dublin, Irel...",Figma,Business Operations,"Dublin, Ireland",Figma is growing our team of passionate creati...
641,"Backend Engineer/API, Payments and Risk",Stripe,8556 LPM Core - Eng,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
644,Business Partner Analyst,Stripe,4159 Risk Ops S&A,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
686,Engagement Manager,Stripe,1143 EMEA Delivery,"Dublin, Ireland",Who we are\n \n\n\nAbout Stripe\n\n\nStripe is...
706,Enterprise Support Specialist,Stripe,4119 Product Support,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
722,"Financial Data Analyst, Technical Operations",Stripe,8546 MMS Platform - Eng,"Dublin, Ireland",Who we are \n\n\nAbout Stripe\n\n\nStripe is a...
773,Integration Engineer,Stripe,1140 Professional Services,Ireland,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
967,"Software Engineer, Payments and Risk",Stripe,8216 Risk Onboarding and Trusted Users,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1015,"Technical Account Manager, Risk",Stripe,"4149 Technical Account Management, Support & S...","Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1027,"Technical Partner Manager, EMEA Payment Methods",Stripe,3515 Partner Engineering and Operations,"Ireland-Dublin, UK-London, Ireland-remote, UK-...",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1119,"Senior Accountant (Dublin, Ireland)",Figma,Business Operations,"Dublin, Ireland",Figma is growing our team of passionate creati...
1157,"Sales Manager, Startups",Stripe,1180 GEO Sales HQ (EMEA),"Dublin, Ireland",About the team\n\n\nThe EMEA Startup team is a...
1163,"Product Manager, EMEA Payments Lead",Stripe,8555 Payments Globalization - PM,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1173,Security Engineer - Offensive Security,Stripe,8611 Security Analytics,Ireland,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1174,Security Engineer - Threat Detection,Stripe,8611 Security Analytics,Ireland,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1191,EMEA People Operations Shared Service Specialist,Riot Games,People,"Dublin, Ireland","As an essential part of our People Team, you w..."
1192,EMEA Tax Manager (13 Month Contract),Riot Games,Finance & Strategy,"Dublin, Ireland",The Global Tax team at Riot is dedicated to he...
1341,Account Executive - Field Sales,Flipdish,Field Sales,Ireland - Limerick (Remote),"At Flipdish, we’re turning the tables in favou..."
1342,Account Executive - Field Sales,Flipdish,Field Sales,Ireland - Galway (Remote),"At Flipdish, we’re turning the tables in favou..."
1352,Financial Accountant,Flipdish,Finance,Ireland - Dublin Hub (Hybrid),"At Flipdish, we’re turning the tables in favou..."
1353,People Associate,Flipdish,People,Ireland - Dublin Hub (Hybrid),"At Flipdish, we’re turning the tables in favou..."
1386,Lead Technical Artist,2K,Animation - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\n2K is headquartered in Novato,..."
1463,Senior VFX Artist,2K,Art - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\n2K is headquartered in Novato,..."
1824,"Customer Success Manager, Mid-Market",Greenhouse,Customer Success,Anywhere in Ireland,Our \nmission\n at Greenhouse is to make every...
1825,Don’t see what you’re looking for?,Greenhouse,Customer Success,"Dublin, Ireland",Our \nmission\n at Greenhouse is to make every...
1830,Don’t see what you’re looking for?,Greenhouse,Sales,Anywhere in Ireland,Our \nmission\n at Greenhouse is to make every...
1851,"Manager, Customer Success (Fixed-term contract)",Greenhouse,Customer Success,Anywhere in Ireland,Our \nmission\n at Greenhouse is to make every...
1862,Information Security Engineer,G-P,IT,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1863,Office Co-Ordinator,G-P,Finance,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1865,Principal Partner Platform Advocate,G-P,Product,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1872,Senior Software Engineer,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1874,Senior Software Engineer,G-P,Technology,United Kingdom - Northern Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1875,Software Engineer II,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1894,Senior Software Engineer,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1895,Senior Software Engineer,G-P,Technology,United Kingdom - Northern Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1900,Staff Software Engineer,G-P,Technology,United Kingdom - Northern Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1901,Staff Software Engineer,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1902,Technical Operational Manager,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1968,Business Partner Analyst,Stripe,4176 Support S&A,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1989,"Data Analyst, Financial Enablement",Stripe,7420 Finance Systems,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
2045,"Manager, Global Sanctions",Stripe,3313 SDC - Financial Crimes,Ireland,Who we are \n\n\nAbout Stripe\n\n\nStripe is a...
2074,"Product Designer, Global",Stripe,8811 Product Design,Ireland,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
2136,"Solutions Architect, Commercial, UK",Stripe,1150 Solutions Architecture,"Dublin, Ireland",Who we are \n\n\nAbout Stripe\n\n\nStripe is a...
2141,"Solutions Architect, Startups and SMB",Stripe,1150 Solutions Architecture,"Dublin, Ireland",Who we are \n\n\nAbout Stripe\n\n\nStripe is a...
2234,Staff Software Engineer,Riot Games,Riot Technology,"Dublin, Ireland; Los Angeles, USA","As a part of the Riot Infrastructure Team, you..."
2261,CRM Specialist,2K,Global Marketing Player Connections - 2K Publi...,"Dublin, Ireland","Who We Are\n\n\nAt 2K, we create some of the m..."
2272,Lead Technical Artist,2K,Animation - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\n2K is headquartered in Novato,..."
2308,Staff Data Analyst,2K,Core Tech/Tools Development - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\nAt 2K, we create some of the m..."
2485,Customer Adoption Manager,G-P,Sales,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
2496,Sales Executive,G-P,Sales,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
2499,Sr. Director & Head of Architecture,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
2529,"Product Designer, Risk",Stripe,8811 Product Design,Ireland / United Kingdom,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
2552,Director of Data Engineering,2K,Core Tech/Tools Development - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\nAt 2K, we create some of the m..."
2559,Senior Expert Gameplay Animator,2K,Art - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\nAt 2K, we create some of the m..."
2577,Sr. Director & Head of Architecture,G-P,Technology,United Kingdom - Northern Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...

,title,company,department,location,description
554,"Senior Technical Revenue Analyst (Dublin, Irel...",Figma,Business Operations,"Dublin, Ireland",Figma is growing our team of passionate creati...
641,"Backend Engineer/API, Payments and Risk",Stripe,8556 LPM Core - Eng,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
644,Business Partner Analyst,Stripe,4159 Risk Ops S&A,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
686,Engagement Manager,Stripe,1143 EMEA Delivery,"Dublin, Ireland",Who we are\n \n\n\nAbout Stripe\n\n\nStripe is...
706,Enterprise Support Specialist,Stripe,4119 Product Support,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
722,"Financial Data Analyst, Technical Operations",Stripe,8546 MMS Platform - Eng,"Dublin, Ireland",Who we are \n\n\nAbout Stripe\n\n\nStripe is a...
773,Integration Engineer,Stripe,1140 Professional Services,Ireland,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
967,"Software Engineer, Payments and Risk",Stripe,8216 Risk Onboarding and Trusted Users,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1015,"Technical Account Manager, Risk",Stripe,"4149 Technical Account Management, Support & S...","Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1027,"Technical Partner Manager, EMEA Payment Methods",Stripe,3515 Partner Engineering and Operations,"Ireland-Dublin, UK-London, Ireland-remote, UK-...",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1119,"Senior Accountant (Dublin, Ireland)",Figma,Business Operations,"Dublin, Ireland",Figma is growing our team of passionate creati...
1157,"Sales Manager, Startups",Stripe,1180 GEO Sales HQ (EMEA),"Dublin, Ireland",About the team\n\n\nThe EMEA Startup team is a...
1163,"Product Manager, EMEA Payments Lead",Stripe,8555 Payments Globalization - PM,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1173,Security Engineer - Offensive Security,Stripe,8611 Security Analytics,Ireland,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1174,Security Engineer - Threat Detection,Stripe,8611 Security Analytics,Ireland,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1191,EMEA People Operations Shared Service Specialist,Riot Games,People,"Dublin, Ireland","As an essential part of our People Team, you w..."
1192,EMEA Tax Manager (13 Month Contract),Riot Games,Finance & Strategy,"Dublin, Ireland",The Global Tax team at Riot is dedicated to he...
1341,Account Executive - Field Sales,Flipdish,Field Sales,Ireland - Limerick (Remote),"At Flipdish, we’re turning the tables in favou..."
1342,Account Executive - Field Sales,Flipdish,Field Sales,Ireland - Galway (Remote),"At Flipdish, we’re turning the tables in favou..."
1352,Financial Accountant,Flipdish,Finance,Ireland - Dublin Hub (Hybrid),"At Flipdish, we’re turning the tables in favou..."
1353,People Associate,Flipdish,People,Ireland - Dublin Hub (Hybrid),"At Flipdish, we’re turning the tables in favou..."
1386,Lead Technical Artist,2K,Animation - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\n2K is headquartered in Novato,..."
1463,Senior VFX Artist,2K,Art - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\n2K is headquartered in Novato,..."
1824,"Customer Success Manager, Mid-Market",Greenhouse,Customer Success,Anywhere in Ireland,Our \nmission\n at Greenhouse is to make every...
1825,Don’t see what you’re looking for?,Greenhouse,Customer Success,"Dublin, Ireland",Our \nmission\n at Greenhouse is to make every...
1830,Don’t see what you’re looking for?,Greenhouse,Sales,Anywhere in Ireland,Our \nmission\n at Greenhouse is to make every...
1851,"Manager, Customer Success (Fixed-term contract)",Greenhouse,Customer Success,Anywhere in Ireland,Our \nmission\n at Greenhouse is to make every...
1862,Information Security Engineer,G-P,IT,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1863,Office Co-Ordinator,G-P,Finance,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1865,Principal Partner Platform Advocate,G-P,Product,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1872,Senior Software Engineer,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1874,Senior Software Engineer,G-P,Technology,United Kingdom - Northern Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1875,Software Engineer II,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1894,Senior Software Engineer,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1895,Senior Software Engineer,G-P,Technology,United Kingdom - Northern Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1900,Staff Software Engineer,G-P,Technology,United Kingdom - Northern Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1901,Staff Software Engineer,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1902,Technical Operational Manager,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
1968,Business Partner Analyst,Stripe,4176 Support S&A,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
1989,"Data Analyst, Financial Enablement",Stripe,7420 Finance Systems,"Dublin, Ireland",Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
2045,"Manager, Global Sanctions",Stripe,3313 SDC - Financial Crimes,Ireland,Who we are \n\n\nAbout Stripe\n\n\nStripe is a...
2074,"Product Designer, Global",Stripe,8811 Product Design,Ireland,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
2136,"Solutions Architect, Commercial, UK",Stripe,1150 Solutions Architecture,"Dublin, Ireland",Who we are \n\n\nAbout Stripe\n\n\nStripe is a...
2141,"Solutions Architect, Startups and SMB",Stripe,1150 Solutions Architecture,"Dublin, Ireland",Who we are \n\n\nAbout Stripe\n\n\nStripe is a...
2234,Staff Software Engineer,Riot Games,Riot Technology,"Dublin, Ireland; Los Angeles, USA","As a part of the Riot Infrastructure Team, you..."
2261,CRM Specialist,2K,Global Marketing Player Connections - 2K Publi...,"Dublin, Ireland","Who We Are\n\n\nAt 2K, we create some of the m..."
2272,Lead Technical Artist,2K,Animation - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\n2K is headquartered in Novato,..."
2308,Staff Data Analyst,2K,Core Tech/Tools Development - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\nAt 2K, we create some of the m..."
2485,Customer Adoption Manager,G-P,Sales,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
2496,Sales Executive,G-P,Sales,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
2499,Sr. Director & Head of Architecture,G-P,Technology,Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...
2529,"Product Designer, Risk",Stripe,8811 Product Design,Ireland / United Kingdom,Who we are\n\n\nAbout Stripe\n\n\nStripe is a ...
2552,Director of Data Engineering,2K,Core Tech/Tools Development - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\nAt 2K, we create some of the m..."
2559,Senior Expert Gameplay Animator,2K,Art - 2K Publishing,"Dublin, Ireland","Who We Are\n\n\nAt 2K, we create some of the m..."
2577,Sr. Director & Head of Architecture,G-P,Technology,United Kingdom - Northern Ireland (Remote-First),About Us\n\n\nOur leading SaaS-based Global Em...